# Dev用flyを本番用に格上げしたい時に、ローカルのflyフォルダを更新することで、自動でデプロイするワークフロウ。
name: Fly Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'fly/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to production
        run: flyctl deploy --remote-only
        working-directory: fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}